name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check:
    name: Check Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: latest
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: pnpm install
      - run: pnpm prettier --check .
      - run: pnpm tsc --noEmit
